// Auto-generated by build.rs using bindgen over the Steinberg ASIO SDK headers.
// Do not edit manually — this file is regenerated on every build.
#![allow(
    non_camel_case_types,
    non_upper_case_globals,
    non_snake_case,
    dead_code,
    unused,
    clippy::all
)]
include!(concat!(env!("OUT_DIR"), "/asio_bindings.rs"));
